export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const OPEN_ACCOUNT_MODAL = "OPEN_ACCOUNT_MODAL";
export const CLOSE_ACCOUNT_MODAL = "CLOSE_ACCOUNT_MODAL";
export const SET_VISIBLE_ACCOUNT = "SET_VISIBLE_ACCOUNT";
